### ISSUE TITLE
Add an API to get the Exposed Port of a Service

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/deployment-manager#3]
Docker Compose exposed the [port API](). We are gonna rely on it to get the exposed port of services started without an host minded port (e.g., the BenchFlow services).

Example of API call with curl:

`curl --insecure http://<SWARM_IP>:<SPARM_PORT>/containers/json?filters=%7B%22name%22%3A%5B%22<CONTAINER_NAME>*%22%5D%7D`

with \* after the name of the service for with I want the port, that I define statically (e.g., stats*)

**OR Better:** I can directly use docker compose: docker-compose port mysql 8080 [I just need the name of the service, but is is easy, but it easy because I can define a taxonomy and hardcode it]

You get IP and Public port in the response, and that’s it. You can use them to connect to the service, by getting the dynamic port allocated. This will also be useful when we will not use anymore the net=“host” and we want to get all the dynamic info at runtime and it just rely on docker

then update the [driver](https://github.com/benchflow/client)

**Comment by simonedavico** [comment]
Wasn't this implemented by [this pull request](https://github.com/benchflow/compose/pull/4)?

**Comment by VincenzoFerme** [comment]
Right

**Comment by VincenzoFerme** [comment]
Right
